### PR TITLE
Slice issue fix

### LINKED ISSUE #58: An entire file should be a valid slice range
### Repro Steps

- Visit https://gist.github.com/jwparsons/b8bcfe1023296fabe6eb66dbfbaa684e
- Notice that `test.cpp` has 34 lines
- Visit https://digist.azurewebsites.net/gist/b8bcfe1023296fabe6eb66dbfbaa684e?file=test.cpp&slice=14:34
- Notice that an invalid range error appears
- Visit https://digist.azurewebsites.net/gist/b8bcfe1023296fabe6eb66dbfbaa684e?file=test.cpp&slice=14:33
- Notice that the request returns successfully

I'd expect `https://digist.azurewebsites.net/gist/b8bcfe1023296fabe6eb66dbfbaa684e?file=test.cpp&slice=14:34` to be a valid request since `test.cpp` has 34 lines.

### PR DESCRIPTION
**Pull request by KartikM123**
### Completed

- Fixed range issue. Was not considering that _x_ "\n" characters would create _x+1_ lines.

Closes #58

### CODE REVIEW

File: routes/gistProvider.js [hunk 1]
```diff
@@ -87,7 +87,7 @@ function checkFileExists(file, gistInfo){
 
 function checkSliceInFile(file, gistInfo, start, stop){
     let totalLines = gistInfo[file]["content"].split("\n").length;
-    return ((totalLines > start) && (totalLines > stop));
+    return ((totalLines >= start) && (totalLines >= stop));
```
Comment (jwparsons) [inline routes/gistProvider.js:90]: I think
`(start <= totalLines) && (stop <= totalLines)`
makes more sense from a code readability standpoint.

Comment (KartikM123) [reply routes/gistProvider.js:90]: yes will fix
